title: Arsalan Esmaeili
description: Ph.D. Candidate in Transportation Engineering @ UW
remote_theme: pages-themes/cayman@v0.2.0 # A cleaner, more modern minimal theme
plugins:
  - jekyll-remote-theme

# Navigation Links
header_pages:
  - index.md
  - projects.md
  - publications.md

# Professional IDs
google_scholar: YOUR_SCHOLAR_ID
linkedin: arsalan-esmaili
github: arsalanesmaili
